const DATA_URL='../vedator/episodes.json';
const state={lang:localStorage.getItem('vedator.lang')==='cs'?'cs':'sk',view:'episodes',topic:'all',episodes:[],locales:{},episodeText:{cs:{},sk:{}},questions:{cs:[],sk:[]},loading:true};

const TOPICS=[
  {id:'all',label:'topic_all',words:[]},
  {id:'space',label:'topic_space',words:['vesmír','vesmir','hviezd','hvezd','planét','planet','galaxi','slnko','slunce','mesiac','mesic','mimozem']},
  {id:'black_holes',label:'topic_black_holes',words:['čierna diera','cierna diera','černá díra','cerna dira','hawking','singularit']},
  {id:'quantum',label:'topic_quantum',words:['kvant','superpoz','previazan','spleten','orbital','váku','vakuu']},
  {id:'relativity',label:'topic_relativity',words:['relativ','gravit','časopriestor','casopriestor','časoprostor','casoprostor','rychlost svetla','rýchlosť svetla']},
  {id:'math',label:'topic_math',words:['matemat','prvočís','prvocis','nekoneč','nekonec','paradox','teória hier','teorie her']},
  {id:'biology',label:'topic_biology',words:['biolog','medic','vitam','genet','gén','gen','mozog','mozek','spán','span','vajíč','vajic','spermi']},
  {id:'technology',label:'topic_technology',words:['technol','počítač','pocitac','umelá inteligencia','umělá inteligence',' ai ','mikrovln','gps','batéri','bateri','vodík','vodik']},
  {id:'earth',label:'topic_earth',words:['zem','oceán','ocean','ľadovec','ledovec','sopk','tornád','tornado','počas','pocasi','atmosfér','atmosfer','klím','klim']},
  {id:'chemistry',label:'topic_chemistry',words:['chémi','chemi','atóm','atom','molekul','prvok','prvek','hélium','helium','deutéri','deuteri']},
  {id:'society',label:'topic_society',words:['spoloč','spolec','psychol','ekonom','peniaz','peněz','jazyk','právo','pravo']}
];

const SERIES=[
  {id:'faq',label:'series_faq',test:e=>/faq|dobr[ée] ot[áa]zk/i.test(e.title)},
  {id:'alien',label:'series_alien',test:e=>/mimozem|f(?:ermi|ermiho)|drake/i.test(`${e.title} ${plain(e.description)}`)},
  {id:'space_talks',label:'series_space_talks',test:e=>/rozhovor.*vesm[ií]r|vesm[ií]r.*rozhovor/i.test(e.title)},
  {id:'genetics',label:'series_genetics',test:e=>/genetick[ýy].*speci[áa]l/i.test(e.title)},
  {id:'nobel',label:'series_nobel',test:e=>/nobel/i.test(e.title)},
  {id:'math',label:'series_math',test:e=>TOPICS.find(x=>x.id==='math').words.some(w=>norm(`${e.title} ${plain(e.description)}`).includes(norm(w)))}
];

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function plain(html=''){const d=document.createElement('div');d.innerHTML=html;return(d.textContent||'').replace(/\s+/g,' ').trim()}
function norm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function t(key,vars={}){let value=state.locales[state.lang]?.[key]??key;for(const[k,v]of Object.entries(vars))value=value.replaceAll(`{${k}}`,v);return value}
function localizedEpisode(e){const override=state.episodeText[state.lang]?.[String(e.number)]||{};return{...e,title:override.title||e.title,description:override.description||plain(e.description)}}
function searchableEpisode(e){const source=`${e.title} ${plain(e.description)}`;const cs=state.episodeText.cs?.[String(e.number)]||{};return norm(`${source} ${cs.title||''} ${cs.description||''}`)}
function topicFor(e){const txt=searchableEpisode(e);return TOPICS.filter(x=>x.id!=='all'&&x.words.some(w=>txt.includes(norm(w)))).map(x=>x.id)}
function dateText(value){if(!value)return'';const d=new Date(value);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat(state.lang==='sk'?'sk-SK':'cs-CZ',{day:'numeric',month:'long',year:'numeric'}).format(d)}
function sortOptions(){const select=$('#sort');const options=state.view==='series'?[['count','seriesCount'],['alpha','alphabetical'],['first','firstEpisode']]:[['new','newest'],['old','oldest'],['number','number']];const old=select.value;select.innerHTML=options.map(([v,k])=>`<option value="${v}">${esc(t(k))}</option>`).join('');if(options.some(([v])=>v===old))select.value=old}
function applyStaticText(){document.documentElement.lang=state.lang;document.title=t('appTitle');$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));$('#search').placeholder=t('searchPlaceholder');$$('[data-language]').forEach(b=>b.classList.toggle('active',b.dataset.language===state.lang));sortOptions()}

async function loadJson(url,fallback){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));return await r.json()}catch{return fallback}}
async function loadAll(){state.loading=true;render();const [sk,cs,epsCs,epsSk,qCs,qSk]=await Promise.all([loadJson('locales/sk.json',{}),loadJson('locales/cs.json',{}),loadJson('content/episodes.cs.json',{}),loadJson('content/episodes.sk.json',{}),loadJson('content/questions.cs.json',[]),loadJson('content/questions.sk.json',[])]);state.locales={sk,cs};state.episodeText={cs:epsCs,sk:epsSk};state.questions={cs:qCs,sk:qSk};applyStaticText();await loadEpisodes()}
async function loadEpisodes(){state.loading=true;render();try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();state.episodes=Array.isArray(data)?data:(data.episodes||[]);localStorage.setItem('vedator.episodes',JSON.stringify(state.episodes));state.loading=false;render()}catch(error){const saved=localStorage.getItem('vedator.episodes');if(saved){state.episodes=JSON.parse(saved);state.loading=false;render()}else{state.loading=false;$('#count').textContent=t('noData');$('#content').innerHTML=`<div class="status"><strong>${esc(t('loadError'))}</strong><br>${esc(error.message)}</div>`}}}

function filteredEpisodes(){const q=norm($('#search').value);return state.episodes.filter(e=>{const bySearch=!q||q.split(' ').every(w=>searchableEpisode(e).includes(w));const cats=topicFor(e);const byTopic=state.topic==='all'||cats.includes(state.topic);return bySearch&&byTopic}).map(e=>({...localizedEpisode(e),cats:topicFor(e)}))}
function episodeQuestions(number){return state.questions[state.lang].filter(q=>Number(q.episode)===Number(number))}
function summaryHtml(number){const list=episodeQuestions(number);if(!list.length)return'';return`<details class="summary"><summary>${esc(t('episodeSummary'))}</summary><div class="summary-body">${list.map(q=>`<div class="summary-block"><div class="summary-time">${esc(q.time)}</div><div class="summary-title">${esc(q.title)}</div>${q.question?`<div class="summary-question">${esc(t('questionLabel'))}: ${esc(q.question)}</div>`:''}<ul>${q.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div>`).join('')}<div class="date">${esc(t('summaryNote'))}</div></div></details>`}
function episodeCard(e){const description=(e.description||'').replace(/Podcast vzniká[\s\S]*/i,'').trim();const cats=e.cats.length?e.cats:['other'];return`<article class="card"><div class="date">${esc(dateText(e.date))}</div><h2>${esc(e.title)}</h2><div class="desc">${esc(description||t('descriptionMissing'))}</div><div class="tags">${cats.map(id=>`<span class="tag">${esc(id==='other'?t('other'):t(TOPICS.find(x=>x.id===id)?.label||id))}</span>`).join('')}</div><div class="links">${e.enclosure?`<a class="primary" href="${esc(e.enclosure)}" target="_blank" rel="noopener">${esc(t('play'))}</a>`:''}<a class="secondary" href="${esc(e.link||e.enclosure||'#')}" target="_blank" rel="noopener">${esc(t('episodeDetail'))}</a></div>${summaryHtml(e.number)}</article>`}
function renderEpisodes(){let arr=filteredEpisodes();const mode=$('#sort').value||'new';arr.sort((a,b)=>mode==='old'?new Date(a.date)-new Date(b.date):mode==='number'?(b.number||0)-(a.number||0):new Date(b.date)-new Date(a.date));$('#count').textContent=t('foundEpisodes',{shown:arr.length,total:state.episodes.length});$('#content').innerHTML=arr.length?arr.map(episodeCard).join(''):`<div class="status">${esc(t('nothingFound'))}</div>`}
function seriesGroups(){const groups=SERIES.map(s=>({name:t(s.label),items:state.episodes.filter(s.test).sort((a,b)=>new Date(a.date)-new Date(b.date))})).filter(g=>g.items.length>=2);const mode=$('#sort').value||'count';groups.sort((a,b)=>mode==='alpha'?a.name.localeCompare(b.name,state.lang):mode==='first'?new Date(a.items[0].date)-new Date(b.items[0].date):b.items.length-a.items.length||a.name.localeCompare(b.name,state.lang));return groups}
function renderSeries(){const groups=seriesGroups();$('#count').textContent=t('foundSeries',{count:groups.length});$('#content').innerHTML=groups.length?groups.map(g=>`<details class="series-card"><summary><span>${esc(g.name)}</span><span>${g.items.length} ${esc(t('episodesUnit'))}</span></summary><div class="series-body"><ol>${g.items.map(raw=>{const e=localizedEpisode(raw);return`<li><a href="${esc(e.link||e.enclosure||'#')}" target="_blank" rel="noopener">${esc(e.title)}</a></li>`}).join('')}</ol></div></details>`).join(''):`<div class="status">${esc(t('nothingFound'))}</div>`}
function questionCard(q){const ep=state.episodes.find(e=>Number(e.number)===Number(q.episode));const href=ep?.enclosure||ep?.link||'#';return`<article class="card question-card"><div class="question-meta">${esc(localizedEpisode(ep||{number:q.episode,title:`Podcast ${q.episode}`}).title)} • ${esc(q.time)}</div><h2>${esc(q.title)}</h2>${q.question?`<div class="summary-question">${esc(t('questionLabel'))}: ${esc(q.question)}</div>`:''}<div class="question-answer"><ul>${q.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div><div class="links"><a class="primary" href="${esc(href)}" target="_blank" rel="noopener">${esc(t('play'))}</a></div></article>`}
function renderQuestions(){const term=norm($('#search').value);let list=state.questions[state.lang].filter(q=>{const cats=topicFor({title:q.title,description:q.points.join(' '),number:q.episode});return(!term||norm(`${q.title} ${q.question||''} ${q.points.join(' ')}`).includes(term))&&(state.topic==='all'||cats.includes(state.topic))});const mode=$('#sort').value||'new';list.sort((a,b)=>mode==='old'?a.episode-b.episode:b.episode-a.episode||a.time.localeCompare(b.time));$('#count').textContent=t('foundQuestions',{count:list.length});$('#content').innerHTML=list.length?list.map(questionCard).join(''):`<div class="status">${esc(t('nothingFound'))}</div>`}
function renderTopics(){const box=$('#topics');box.innerHTML=TOPICS.map(x=>`<button type="button" class="topic${state.topic===x.id?' active':''}" data-topic="${x.id}">${esc(t(x.label))}</button>`).join('');box.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;render()})}
function render(){if(!state.locales[state.lang]){if($('#count'))$('#count').textContent='…';return}applyStaticText();renderTopics();$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));if(state.loading){$('#count').textContent=t('loading');$('#content').innerHTML=`<div class="status">${esc(t('loading'))}</div>`;return}if(state.view==='episodes')renderEpisodes();else if(state.view==='series')renderSeries();else renderQuestions()}

$$('[data-language]').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.language;localStorage.setItem('vedator.lang',state.lang);state.topic='all';render()}));$$('.tab').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;state.topic='all';sortOptions();render()}));$('#search').addEventListener('input',render);$('#sort').addEventListener('change',render);$('#refresh').addEventListener('click',loadEpisodes);
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});$('#installApp').addEventListener('click',async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else alert(state.lang==='sk'?'Inštaláciu otvorte v ponuke prehliadača a zvoľte Pridať na plochu.':'Instalaci otevřete v nabídce prohlížeče a zvolte Přidat na plochu.')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
loadAll();
