(()=>{
if(window.__vedatorPlaylistPatch)return;window.__vedatorPlaylistPatch=true;
const KEY='vedator-user-playlists-v1',HASH='playlist',A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const FAQ=[340,337,332,326,319,313,300,295,289,284,278,272,270,263,257,248,244,226,218,211,203,190,179,170,158,143,133,128,119,112,100,89,82];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const sec=v=>{const p=String(v||'').match(/\d{1,2}:\d{2}(?::\d{2})?/)?.[0].split(':').map(Number);return!p?0:p.length===3?p[0]*3600+p[1]*60+p[2]:p[0]*60+p[1]};
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(36).slice(2);
const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}},save=x=>localStorage.setItem(KEY,JSON.stringify(x));
const eps=()=>{try{return Array.isArray(episodes)?episodes:[]}catch{return[]}},epNum=n=>eps().find(e=>Number(e.number)===Number(n))||null,epId=e=>String(e?.id||e?.number||e?.title||''),epOld=id=>eps().find(e=>epId(e)===String(id))||null;
const enc=n=>Number.isInteger(n)&&n>=0&&n<4096?A[(n>>6)&63]+A[n&63]:'';
const dec=s=>s?.length===2?((A.indexOf(s[0])<<6)|A.indexOf(s[1])):-1;
const epRef=n=>enc(Number(n)),qRef=i=>enc(2048+i),isRef=x=>typeof x==='string'&&x.length===2&&dec(x)>=0;
let questions=null,questionsPromise=null;
async function loadQuestions(){if(questions)return questions;if(questionsPromise)return questionsPromise;questionsPromise=(async()=>{const out=[];for(const n of FAQ){if(n===300&&window.SUMMARIES?.[300]?.sections){SUMMARIES[300].sections.forEach((x,i)=>out.push({episode:n,order:i,time:x.time||'0:00',title:String(x.title||`Otázka ${i+1}`).replace(/^\s*\d+\)\s*/,''),points:[...(x.items||[])]}));continue}const a=document.createElement('article');a.hidden=true;a.innerHTML=`<h2>Podcast ${n}</h2>`;document.querySelector('#episodes')?.append(a);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));[...a.querySelectorAll('.summary-block')].forEach((b,i)=>out.push({episode:n,order:i,time:b.querySelector('.summary-time')?.textContent||'0:00',title:b.querySelector('.summary-title')?.textContent||`Otázka ${i+1}`,points:[...b.querySelectorAll('li')].map(x=>x.textContent.trim())}));a.remove()}questions=out;return out})();return questionsPromise}
function normalizeRef(x){if(isRef(x))return x;const e=epOld(x);return e?epRef(e.number):''}
function itemInfo(ref){const v=dec(ref);if(v<0)return null;if(v<2048){const e=epNum(v);return e?{type:'e',ref,episode:e,title:e.title,subtitle:`Díl ${e.number}`} : null}const q=questions?.[v-2048];if(!q)return null;const e=epNum(q.episode);return e?{type:'q',ref,episode:e,question:q,title:q.title,subtitle:`Díl ${q.episode} • ${q.time}`} : null}
function b64e(s){const b=new TextEncoder().encode(s);let x='';b.forEach(v=>x+=String.fromCharCode(v));return btoa(x).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64d(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return new TextDecoder().decode(Uint8Array.from(atob(s),c=>c.charCodeAt(0)))}
const style=document.createElement('style');style.textContent=`
.vedator-playlist-view{display:none}.vedator-playlist-view.active{display:block}.vedator-playlist-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:18px 0 12px}.vedator-playlist-add{width:44px;height:44px;border-radius:50%;border:0;background:var(--accent);color:#fff;font-size:1.8rem;cursor:pointer}.vedator-playlist-list{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;align-items:start}details.vedator-playlist-card{background:var(--card);border:1px solid var(--line);border-radius:16px;overflow:hidden}.vedator-playlist-card summary{display:flex;align-items:center;gap:8px;padding:14px 16px;cursor:pointer;list-style:none}.vedator-playlist-title{font-weight:800;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.vedator-playlist-count,.vedator-item-sub{color:var(--muted);font-size:.84rem}.vedator-playlist-actions{display:flex}.vedator-playlist-icon{border:0;background:transparent;color:var(--muted);cursor:pointer;padding:6px}.vedator-playlist-body{border-top:1px solid var(--line);padding:5px 14px 10px;max-height:360px;overflow:auto}.vedator-playlist-items{list-style:none;margin:0;padding:0}.vedator-playlist-item{border-bottom:1px solid var(--line)}.vedator-playlist-open{display:block;width:100%;border:0;background:transparent;color:var(--ink);text-align:left;padding:11px 3px;cursor:pointer;font:inherit}.vedator-playlist-open:hover{color:var(--accent)}.vedator-playlist-empty{padding:24px;text-align:center;color:var(--muted)}
.vedator-editor{position:fixed;inset:0;z-index:10000;background:rgba(3,7,18,.72);display:flex;align-items:center;justify-content:center;padding:16px}.vedator-editor.hidden{display:none}.vedator-editor-box{width:min(920px,100%);height:min(88vh,850px);display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;background:var(--card);color:var(--ink);border:1px solid var(--line);border-radius:20px;overflow:hidden}.vedator-editor-head,.vedator-editor-foot{display:flex;align-items:center;gap:10px;padding:14px 16px}.vedator-editor-head{border-bottom:1px solid var(--line)}.vedator-editor-head strong{flex:1}.vedator-editor-close{border:0;background:transparent;color:var(--muted);font-size:1.3rem}.vedator-source-switch{display:flex;gap:6px;padding:10px 16px;border-bottom:1px solid var(--line)}.vedator-source-switch button{border:1px solid var(--line);background:transparent;color:var(--ink);border-radius:999px;padding:8px 14px;cursor:pointer;font-weight:750}.vedator-source-switch button.active{background:var(--accent);border-color:var(--accent);color:#fff}.vedator-editor-columns{display:grid;grid-template-columns:1fr 1fr;min-height:0}.vedator-editor-pane{display:grid;grid-template-rows:auto minmax(0,1fr);min-height:0;padding:14px 14px 0}.vedator-editor-pane+.vedator-editor-pane{border-left:1px solid var(--line)}.vedator-editor-scroll{overflow:auto;min-height:0;padding-bottom:14px}.vedator-editor-search{width:100%;box-sizing:border-box;margin:0 0 10px;padding:11px 13px;border:1px solid var(--line);border-radius:12px;background:var(--card);color:var(--ink);font:inherit}.vedator-editor-list,.vedator-edit-order{display:grid;gap:8px}.vedator-editor-choice,.vedator-edit-row{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;border:1px solid var(--line);border-radius:12px;padding:10px 12px}.vedator-editor-choice{cursor:pointer}.vedator-editor-choice.selected{border-color:var(--accent);background:rgba(124,92,255,.12)}.vedator-edit-controls{display:flex;flex-direction:column}.vedator-edit-move,.vedator-edit-remove{border:0;background:transparent;color:var(--muted);cursor:pointer}.vedator-editor-foot{border-top:1px solid var(--line);justify-content:flex-end}.vedator-editor-save,.vedator-editor-cancel{border-radius:10px;padding:10px 16px;font-weight:750;cursor:pointer}.vedator-editor-save{border:0;background:var(--accent);color:#fff}.vedator-editor-cancel{background:transparent;color:var(--ink);border:1px solid var(--line)}@media(max-width:1000px){.vedator-playlist-list{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.vedator-playlist-list{grid-template-columns:1fr}.vedator-editor-columns{grid-template-columns:1fr;grid-template-rows:1fr 1fr}.vedator-editor-pane+.vedator-editor-pane{border-left:0;border-top:1px solid var(--line)}}`;
document.head.append(style);
const tabs=document.querySelector('.tabs'),episodesSection=document.querySelector('#episodes'),seriesSection=document.querySelector('#series'),topics=document.querySelector('#topics'),episodeSort=document.querySelector('#episodeSort'),seriesSort=document.querySelector('#seriesSort'),count=document.querySelector('#count');if(!tabs||!episodesSection||!seriesSection)return;
const tab=document.createElement('button');tab.type='button';tab.className='tab';tab.dataset.view='playlists';tab.textContent='Playlisty';tabs.append(tab);
const view=document.createElement('section');view.className='vedator-playlist-view';view.innerHTML='<div class="vedator-playlist-toolbar"><strong>Moje playlisty</strong><button class="vedator-playlist-add" type="button">+</button></div><div class="vedator-playlist-list"></div>';seriesSection.after(view);const list=view.querySelector('.vedator-playlist-list');
const editor=document.createElement('div');editor.className='vedator-editor hidden';editor.innerHTML=`<div class="vedator-editor-box"><div class="vedator-editor-head"><strong>Upravit playlist</strong><button class="vedator-editor-close">✕</button></div><div class="vedator-source-switch"><button data-mode="e" class="active">Epizody</button><button data-mode="q">Otázky</button></div><div class="vedator-editor-columns"><section class="vedator-editor-pane"><h3>Přidané položky</h3><div class="vedator-editor-scroll"><div class="vedator-edit-order"></div></div></section><section class="vedator-editor-pane"><div><h3 class="vedator-source-title">Přidat epizody</h3><input class="vedator-editor-search" type="search" placeholder="Hledat epizodu…"></div><div class="vedator-editor-scroll"><div class="vedator-editor-list"></div></div></section></div><div class="vedator-editor-foot"><button class="vedator-editor-cancel">Zrušit</button><button class="vedator-editor-save">Uložit</button></div></div>`;document.body.append(editor);
const order=editor.querySelector('.vedator-edit-order'),choices=editor.querySelector('.vedator-editor-list'),search=editor.querySelector('.vedator-editor-search'),sourceTitle=editor.querySelector('.vedator-source-title');let editId='',draft=[],mode='e';
async function renderEditor(){await loadQuestions();order.innerHTML=draft.length?draft.map((r,i)=>{const x=itemInfo(r);return x?`<div class="vedator-edit-row" data-ref="${r}"><span class="vedator-edit-controls"><button class="vedator-edit-move up" ${i?'':'disabled'}>▲</button><button class="vedator-edit-move down" ${i===draft.length-1?'disabled':''}>▼</button></span><span><b>${esc(x.title)}</b><br><small class="vedator-item-sub">${esc(x.subtitle)}</small></span><button class="vedator-edit-remove">✕</button></div>`:''}).join(''):'<div class="vedator-playlist-empty">Playlist je prázdný.</div>';const q=norm(search.value);const selected=new Set(draft);let data;if(mode==='e')data=eps().map(e=>({ref:epRef(e.number),title:e.title,sub:`#${e.number}`,search:`${e.number} ${e.title} ${e.description||''}`}));else data=questions.map((x,i)=>({ref:qRef(i),title:x.title,sub:`Díl ${x.episode} • ${x.time}`,search:`${x.episode} ${x.title} ${x.points.join(' ')}`}));data=data.filter(x=>!q||norm(x.search).includes(q)).slice(0,300);choices.innerHTML=data.map(x=>`<label class="vedator-editor-choice${selected.has(x.ref)?' selected':''}" data-ref="${x.ref}"><input type="checkbox" ${selected.has(x.ref)?'checked':''}><span>${esc(x.title)}</span><small>${esc(x.sub)}</small></label>`).join('')||'<div class="vedator-playlist-empty">Nic nenalezeno.</div>'}
function show(){document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.toggle('active',x===tab));episodesSection.classList.add('hidden');seriesSection.classList.add('hidden');view.classList.add('active');topics?.classList.add('hidden');episodeSort?.classList.add('hidden');seriesSort?.classList.add('hidden');renderPlaylists()}
document.querySelectorAll('.tabs .tab:not([data-view="playlists"])').forEach(x=>x.addEventListener('click',()=>view.classList.remove('active')));tab.onclick=show;
view.querySelector('.vedator-playlist-add').onclick=()=>{const name=prompt('Název nového playlistu:')?.trim();if(!name)return;const p=load();if(p.some(x=>norm(x.name)===norm(name)))return alert('Playlist s tímto názvem už existuje.');p.push({id:uid(),name,items:[]});save(p);renderPlaylists()};
async function openEditor(id){await loadQuestions();const p=load().find(x=>x.id===id);if(!p)return;editId=id;draft=(p.items||[]).map(normalizeRef).filter(Boolean);mode='e';search.value='';editor.querySelectorAll('.vedator-source-switch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));editor.classList.remove('hidden');renderEditor()}
function close(){editor.classList.add('hidden');editId='';draft=[]}
editor.querySelector('.vedator-source-switch').onclick=e=>{const b=e.target.closest('button[data-mode]');if(!b)return;mode=b.dataset.mode;editor.querySelectorAll('.vedator-source-switch button').forEach(x=>x.classList.toggle('active',x===b));sourceTitle.textContent=mode==='e'?'Přidat epizody':'Přidat otázky';search.placeholder=mode==='e'?'Hledat epizodu…':'Hledat otázku…';search.value='';renderEditor()};search.oninput=renderEditor;
choices.onchange=e=>{const row=e.target.closest('[data-ref]');if(!row)return;const r=row.dataset.ref;if(e.target.checked){if(!draft.includes(r))draft.push(r)}else draft=draft.filter(x=>x!==r);renderEditor()};order.onclick=e=>{const row=e.target.closest('[data-ref]');if(!row)return;const i=draft.indexOf(row.dataset.ref);if(i<0)return;if(e.target.closest('.vedator-edit-remove'))draft.splice(i,1);else if(e.target.closest('.up')&&i>0)[draft[i-1],draft[i]]=[draft[i],draft[i-1]];else if(e.target.closest('.down')&&i<draft.length-1)[draft[i+1],draft[i]]=[draft[i],draft[i+1]];renderEditor()};
editor.querySelector('.vedator-editor-save').onclick=()=>{const p=load(),i=p.findIndex(x=>x.id===editId);if(i>=0){p[i].items=[...draft];save(p)}close();renderPlaylists()};editor.querySelector('.vedator-editor-cancel').onclick=close;editor.querySelector('.vedator-editor-close').onclick=close;editor.onclick=e=>{if(e.target===editor)close()};
function playItem(x,pl){if(!x?.episode?.enclosure)return;const start=x.type==='q'?sec(x.question.time):0;if(x.type==='q')window.__vedatorRequestedStart={episode:x.question.episode,time:start,createdAt:Date.now()};const proxy=document.createElement('article');proxy.hidden=true;proxy.innerHTML='<h2></h2><div class="links"><a class="primary"></a></div>';proxy.querySelector('h2').textContent=x.episode.title;const a=proxy.querySelector('a');a.href=x.episode.enclosure;a.dataset.vedatorEpisodeTitle=x.episode.title;document.body.append(proxy);a.click();proxy.remove()}
async function share(pl){await loadQuestions();const items=(pl.items||[]).map(normalizeRef).filter(Boolean).join('');const payload=b64e(JSON.stringify({v:3,n:pl.name,x:items}));const u=new URL(location.href);u.hash=`${HASH}=${payload}`;try{if(navigator.share)await navigator.share({title:pl.name,text:`Playlist Vedátorského podcastu: ${pl.name}`,url:u.href});else{await navigator.clipboard.writeText(u.href);alert('Odkaz byl zkopírován.')}}catch(e){if(e?.name!=='AbortError')prompt('Zkopírujte odkaz:',u.href)}}
async function importShared(){const m=location.hash.match(new RegExp(`(?:^#|&)${HASH}=([^&]+)`));if(!m)return;try{const d=JSON.parse(b64d(m[1]));let items=[];if(d?.v===3&&typeof d.x==='string'&&d.x.length%2===0)for(let i=0;i<d.x.length;i+=2)items.push(d.x.slice(i,i+2));else if(d?.v===2&&typeof d.e==='string')for(let i=0;i<d.e.length;i+=2)items.push(d.e.slice(i,i+2));else if(Array.isArray(d?.i))items=d.i.map(normalizeRef).filter(Boolean);else return;const name=String(d.n||'Sdílený playlist').trim();if(!confirm(`Uložit sdílený playlist „${name}“?`))return;const p=load();let final=name,n=2;while(p.some(x=>norm(x.name)===norm(final)))final=`${name} (${n++})`;p.push({id:uid(),name:final,items});save(p);history.replaceState(null,'',location.pathname+location.search);setTimeout(show,0)}catch(e){console.warn('Neplatný playlistový odkaz',e)}}
async function renderPlaylists(){await loadQuestions();const p=load();if(count)count.textContent=`${p.length} playlistů`;if(!p.length){list.innerHTML='<div class="vedator-playlist-empty">Zatím nemáte žádný playlist.</div>';return}list.innerHTML=p.map(pl=>{const items=(pl.items||[]).map(normalizeRef).map(itemInfo).filter(Boolean);return `<details class="vedator-playlist-card" data-id="${esc(pl.id)}"><summary><span class="vedator-playlist-title">${esc(pl.name)}</span><span class="vedator-playlist-count">${items.length} položek</span><span class="vedator-playlist-actions"><button class="vedator-playlist-icon edit">✎</button><button class="vedator-playlist-icon share">🔗</button><button class="vedator-playlist-icon delete">🗑</button></span></summary><div class="vedator-playlist-body"><ol class="vedator-playlist-items">${items.length?items.map(x=>`<li class="vedator-playlist-item"><button class="vedator-playlist-open" data-ref="${x.ref}"><b>${esc(x.title)}</b><br><small class="vedator-item-sub">${esc(x.subtitle)}</small></button></li>`).join(''):'<li class="vedator-playlist-empty">Playlist je prázdný.</li>'}</ol></div></details>`}).join('')}
list.onclick=e=>{const card=e.target.closest('[data-id]');if(!card)return;const p=load(),i=p.findIndex(x=>x.id===card.dataset.id);if(i<0)return;if(e.target.closest('.edit')){e.preventDefault();openEditor(p[i].id)}else if(e.target.closest('.share')){e.preventDefault();share(p[i])}else if(e.target.closest('.delete')){e.preventDefault();if(confirm(`Smazat playlist „${p[i].name}“?`)){p.splice(i,1);save(p);renderPlaylists()}}else{const b=e.target.closest('[data-ref]');if(b){e.preventDefault();playItem(itemInfo(b.dataset.ref),p[i])}}};
setTimeout(importShared,700);
})();