(()=>{
const V=window.V,audio=V.$('#audio'),seek=V.$('#audioSeek');
V.episodeContext=()=>V.sortedEpisodes().map(e=>({kind:'episode',episode:e.number,title:e.title,url:e.enclosure,start:null})).filter(x=>x.url);
V.questionContext=(list=V.sortedQuestions())=>list.map(q=>{const e=V.episodeByNumber(q.episode);return e?.enclosure?{kind:'question',episode:q.episode,title:q.title,url:e.enclosure,start:V.parseTime(q.time),questionId:q.id}:null}).filter(Boolean).map((x,i,a)=>({...x,end:a[i+1]?.episode===x.episode?a[i+1].start:null}));
V.openEpisode=(number,start=null,items=null)=>{const raw=V.episodeByNumber(number);if(!raw?.enclosure)return;const e=V.localizedEpisode(raw),item={kind:'episode',episode:e.number,title:e.title,url:e.enclosure,start};V.openAudio(item,items||V.episodeContext())};
V.openQuestion=(id,items=null)=>{const q=V.questionById(id);if(!q)return;const context=items||V.questionContext(),item=context.find(x=>x.questionId===id);if(item)V.openAudio(item,context)};
V.audioKey=item=>`episode-${item.episode}`;
V.saveProgress=(force=false,ended=false)=>{const a=V.state.audio;if(!a.item||a.seeking||audio.readyState===0)return;const duration=Number.isFinite(audio.duration)&&audio.duration>0?audio.duration:(V.state.progress[a.key]?.duration||0),time=ended&&duration?duration:audio.currentTime;if(!Number.isFinite(time)||time<0)return;const second=Math.floor(time);if(!force&&a.lastSaved>=0&&Math.abs(second-a.lastSaved)<5)return;a.lastSaved=second;const previous=V.state.progress[a.key]||{},completed=previous.completed||ended||(duration>0&&(time/duration>=.9||duration-time<=120));V.state.progress[a.key]={currentTime:time,duration,completed,replaying:previous.completed&&!ended,title:a.item.title,updatedAt:Date.now()};V.writeStorage(V.KEYS.progress,V.state.progress);if(V.state.view==='episodes')V.updateEpisodeCard(a.item.episode)};
V.updateEpisodeCard=number=>{const card=document.querySelector(`[data-episode="${number}"]`);if(!card)return;const status=card.querySelector('.listen-status'),h2=card.querySelector('h2'),html=V.listenStatus(number);if(status)status.outerHTML=html||'';else if(html)h2.insertAdjacentHTML('afterend',html);const play=card.querySelector('[data-play-episode]');if(play)play.textContent=V.playLabel(number)};
V.syncAudioUi=()=>{const a=V.state.audio,duration=Number.isFinite(audio.duration)&&audio.duration>0?audio.duration:0;seek.disabled=!duration;seek.max=String(Math.max(1,Math.floor(duration)));if(!a.seeking)seek.value=String(Math.floor(audio.currentTime||0));V.$('#audioCurrent').textContent=V.formatTime(Number(seek.value)||0);V.$('#audioDuration').textContent=duration?V.formatTime(duration):'–:––';V.$('#audioPlayIcon').textContent=audio.paused?'▶':'Ⅱ';V.$('#audioPlay').setAttribute('aria-label',V.t(audio.paused?'play':'pause'));V.$('#audioPrev').disabled=a.index<=0;V.$('#audioNext').disabled=a.index<0||a.index>=a.items.length-1;V.$('#speedValue').textContent=String(a.rate).replace('.',',')+'×'};
V.openAudio=(item,items)=>{V.saveProgress(true);V.state.audio.items=items?.length?items:[item];V.state.audio.index=Math.max(0,V.state.audio.items.findIndex(x=>x.kind===item.kind&&x.episode===item.episode&&(x.questionId||'')===(item.questionId||'')));V.state.audio.item=item;V.state.audio.key=V.audioKey(item);V.state.audio.lastSaved=-1;V.state.audio.restore=null;const record=V.state.progress[V.state.audio.key],start=item.start??(record?.currentTime>10&&(!record.completed||record.replaying)?record.currentTime:0);if(record?.completed&&item.start==null&&!record.replaying){record.currentTime=0;record.replaying=true;V.writeStorage(V.KEYS.progress,V.state.progress)}V.state.audio.restore=start;V.$('#audioTitle').textContent=item.title;V.$('#audioBarTitle').textContent=item.title;V.$('#audioHelp').textContent=start>0?V.t('loadingAt',{time:V.formatTime(start)}):V.t('positionSaved');V.$('#audioModal').hidden=false;document.body.classList.add('body-audio-open');if(!V.state.audio.history){history.pushState({vedatorAudio:true},'');V.state.audio.history=true}audio.pause();audio.src=item.url;audio.playbackRate=V.state.audio.rate;audio.load();audio.onloadedmetadata=()=>{if(V.state.audio.restore!=null){const target=Math.min(V.state.audio.restore,Math.max(0,audio.duration-1));audio.currentTime=target;seek.value=String(Math.floor(target));V.state.audio.restore=null}V.syncAudioUi();audio.play().catch(()=>{V.$('#audioHelp').textContent=V.t('tapPlay')})};if('mediaSession'in navigator&&'MediaMetadata'in window){navigator.mediaSession.metadata=new MediaMetadata({title:item.title,artist:'Vedátorský podcast'});V.setMediaHandlers()}};
V.closeAudio=()=>{V.saveProgress(true);audio.pause();audio.removeAttribute('src');audio.load();V.$('#audioModal').hidden=true;document.body.classList.remove('body-audio-open');V.state.audio.item=null;V.state.audio.key='';V.state.audio.history=false};
V.relativeAudio=delta=>{const i=V.state.audio.index+delta,item=V.state.audio.items[i];if(item)V.openAudio(item,V.state.audio.items)};
V.setMediaHandlers=()=>{const set=(name,fn)=>{try{navigator.mediaSession.setActionHandler(name,fn)}catch{}};set('play',()=>audio.play());set('pause',()=>audio.pause());set('seekbackward',()=>audio.currentTime=Math.max(0,audio.currentTime-10));set('seekforward',()=>audio.currentTime=Math.min(audio.duration||Infinity,audio.currentTime+10));set('previoustrack',()=>V.relativeAudio(-1));set('nexttrack',()=>V.relativeAudio(1))};
V.downloadAudio=async()=>{const url=audio.currentSrc||audio.src;if(!url)return;const label=V.$('#downloadLabel');V.$('#audioDownload').disabled=true;label.textContent=V.t('preparing');try{const r=await fetch(url,{mode:'cors',cache:'no-store'});if(!r.ok)throw Error();const total=Number(r.headers.get('content-length'))||0,reader=r.body?.getReader(),chunks=[];let loaded=0;if(reader){while(true){const{done,value}=await reader.read();if(done)break;chunks.push(value);loaded+=value.byteLength;label.textContent=total?V.t('downloadingPercent',{percent:Math.floor(loaded/total*100)}):V.t('downloading')}}const blob=reader?new Blob(chunks,{type:r.headers.get('content-type')||'audio/mpeg'}):await r.blob(),url2=URL.createObjectURL(blob),a=document.createElement('a');a.href=url2;a.download=V.safeFilename(V.state.audio.item?.title);a.click();setTimeout(()=>URL.revokeObjectURL(url2),30000);V.$('#audioHelp').textContent=V.t('downloaded')}catch{V.$('#audioHelp').textContent=V.t('downloadFailed')}finally{V.$('#audioDownload').disabled=false;label.textContent=V.t('download')}};
audio.addEventListener('timeupdate',()=>{V.syncAudioUi();V.saveProgress(false);const item=V.state.audio.item;if(item?.kind==='question'&&item.end&&audio.currentTime>=item.end-.15){audio.pause();if(V.state.audio.index<V.state.audio.items.length-1)V.relativeAudio(1)}});audio.addEventListener('durationchange',V.syncAudioUi);audio.addEventListener('play',V.syncAudioUi);audio.addEventListener('pause',()=>{V.syncAudioUi();V.saveProgress(true)});audio.addEventListener('ended',()=>V.saveProgress(true,true));seek.addEventListener('pointerdown',()=>V.state.audio.seeking=true);seek.addEventListener('input',()=>{V.$('#audioCurrent').textContent=V.formatTime(seek.value)});seek.addEventListener('change',()=>{audio.currentTime=Number(seek.value)||0;V.state.audio.seeking=false;V.saveProgress(true)});
V.$('#audioClose').onclick=()=>history.back();V.$('#audioPlay').onclick=()=>audio.paused?audio.play():audio.pause();V.$('#audioBack10').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-10);V.$('#audioForward10').onclick=()=>audio.currentTime=Math.min(audio.duration||Infinity,audio.currentTime+10);V.$('#audioPrev').onclick=()=>V.relativeAudio(-1);V.$('#audioNext').onclick=()=>V.relativeAudio(1);V.$('#audioSpeed').onclick=()=>{const i=V.RATES.findIndex(x=>Math.abs(x-V.state.audio.rate)<.001);V.state.audio.rate=V.RATES[(i+1)%V.RATES.length];audio.playbackRate=V.state.audio.rate;V.syncAudioUi()};V.$('#audioDownload').onclick=V.downloadAudio;
window.addEventListener('popstate',()=>{if(!V.$('#audioModal').hidden)V.closeAudio()});window.addEventListener('pagehide',()=>V.saveProgress(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)V.saveProgress(true)});
})();
