(()=>{
if(window.__vedatorQuestionsView)return;window.__vedatorQuestionsView=true;
const FAQ=[340,337,332,326,319,313,300,295,289,284,278,272,270,263,257,248,244,226,218,211,203,190,179,170,158,143,138,133,128,119,112,100,89,82,75,69,60,51,35,26,17],BATCH=20,PREROLL=5,TOTAL_QUESTIONS=719;
const MAP={'Vše':[],'Vesmír':['vesmir','hvezd','hviezd','planet','galaxi','slunce','slnko','mesic','mesiac','jupiter','kosmolog','rozpin'],'Černé díry':['cerna dira','cierna diera','hawking','singularit'],'Kvantová fyzika':['kvant','superpoz','spleten','previazan','orbital','wimp','vakuu','vakua'],'Relativita a gravitace':['relativ','gravit','casoprostor','casopriestor','rychlost svetla'],'Matematika':['matemat','prvocisl','nekonec','paradox','entrop','laplace','tri teles'],'Biologie a medicína':['vitamin','gen','gmo','mozek','mozog','spánek','spanek','zrcadlov','cvičit','cvicit'],'Technologie':['pocitac','počítač','mikrovln','gps','bater','vodik','vodík','auto','klavesnic','klávesnic','tiktok','kryptom'],'Země a příroda':['zeme','země','ocean','ledovec','sopk','tornado','počas','pocasi','vzduch','mrak','atmosfer'],'Chemie':['atom','molekul','prvek','prvok','helium','deuter','voda','jogurt','zlato'],'Ostatní':['podcast','jazyk','wikipedia','anime','videohry','recept','motiv','právo','pravo','plochozem']};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sec=v=>{const p=String(v||'').match(/\d{1,2}:\d{2}(?::\d{2})?/)?.[0].split(':').map(Number);return!p?0:p.length===3?p[0]*3600+p[1]*60+p[2]:p[0]*60+p[1]};
const fmt=value=>{const s=Math.max(0,Math.floor(Number(value)||0)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`};
const shiftTime=value=>fmt(Math.max(0,sec(value)-PREROLL));
const eps=()=>{try{return Array.isArray(episodes)?episodes:[]}catch{return[]}},ep=n=>eps().find(e=>Number(e.number)===Number(n));
const tabs=document.querySelector('.tabs'),episodesBox=document.querySelector('#episodes'),seriesBox=document.querySelector('#series'),topics=document.querySelector('#topics'),count=document.querySelector('#count'),episodeSort=document.querySelector('#episodeSort'),seriesSort=document.querySelector('#seriesSort'),search=document.querySelector('#search');if(!tabs||!episodesBox||!seriesBox||!topics||!search)return;
const currentView=()=>tabs.querySelector('.tab.active')?.dataset.view||'';
const originalRender=window.render;
if(typeof originalRender==='function'&&!originalRender.__vedatorCustomViewGuard){const guardedRender=function(...args){const current=currentView();if(current&&current!=='episodes'&&current!=='series')return;return originalRender.apply(this,args)};guardedRender.__vedatorCustomViewGuard=true;window.render=guardedRender}
function shiftSummaryTimes(root=document){root.querySelectorAll?.('.episode-summary .summary-time:not([data-vedator-preroll])').forEach(node=>{node.textContent=shiftTime(node.textContent);node.dataset.vedatorPreroll=String(PREROLL)})}
shiftSummaryTimes();new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes){if(node.nodeType!==1)continue;if(node.matches?.('.episode-summary .summary-time'))shiftSummaryTimes(node.parentElement||node);shiftSummaryTimes(node)}}).observe(document.body,{childList:true,subtree:true});
const tab=document.createElement('button');tab.type='button';tab.className='tab';tab.dataset.view='questions';tab.textContent='Otázky';const ptab=tabs.querySelector('[data-view="playlists"]');ptab?tabs.insertBefore(tab,ptab):tabs.append(tab);
const qtopics=document.createElement('div');qtopics.className='topics hidden';qtopics.innerHTML=Object.keys(MAP).map((x,i)=>`<button class="topic${i?'':' active'}" data-topic="${esc(x)}">${esc(x)}</button>`).join('');topics.after(qtopics);
const view=document.createElement('section');view.id='questions';view.className='grid hidden';seriesBox.after(view);
const questionSort=document.createElement('select');questionSort.id='questionSort';questionSort.className='sort hidden';questionSort.innerHTML='<option value="new">Nejnovější</option><option value="old">Nejstarší</option>';(seriesSort||episodeSort)?.after(questionSort);
const backTop=document.createElement('button');backTop.id='vedatorBackTop';backTop.type='button';backTop.setAttribute('aria-label','Zpět nahoru');backTop.title='Zpět nahoru';backTop.textContent='↑';document.body.append(backTop);
const style=document.createElement('style');style.textContent='.faq-question-card{min-height:260px}.faq-question-card .faq-meta{color:var(--muted);font-size:.85rem}.faq-question-card .faq-answer{line-height:1.48}.faq-question-card.open .faq-answer{display:block;-webkit-line-clamp:unset}.faq-answer ul{margin:0;padding-left:1.2rem}.faq-answer li{margin:.22rem 0}.faq-question-card .links button{flex:1;text-align:center;border-radius:10px;padding:9px;font:inherit;font-weight:700;cursor:pointer;min-width:0}.faq-play{border:0;background:var(--accent);color:#fff}.faq-more{border:1px solid var(--line);background:#fff;color:var(--ink)}.faq-more.hidden{display:none}.faq-question-card mark{background:#ffe56b;color:#171717;border-radius:3px;padding:0 .08em}.faq-sentinel{grid-column:1/-1;min-height:1px}.faq-loading{grid-column:1/-1;padding:18px;text-align:center;color:var(--muted)}html.theme-dark .faq-more{background:transparent;color:var(--ink)}#vedatorBackTop{position:fixed;right:max(18px,env(safe-area-inset-right));bottom:max(18px,env(safe-area-inset-bottom));z-index:9999;width:48px;height:48px;border:0;border-radius:50%;background:var(--accent);color:#fff;font-size:1.55rem;font-weight:900;box-shadow:0 8px 24px rgba(15,23,42,.28);cursor:pointer;opacity:0;pointer-events:none;transform:translateY(10px);transition:opacity .18s,transform .18s}#vedatorBackTop.visible{opacity:1;pointer-events:auto;transform:none}';document.head.append(style);
let all=[],shown=[],rendered=0,topic='Vše',active=false,io,autoBusy=false,audioObserver=null,loading=false,filterGeneration=0,loadQueue=Promise.resolve();
const loadedEpisodes=new Set(),episodeJobs=new Map();
function updateBackTop(){const scrollable=document.documentElement.scrollHeight>window.innerHeight+120;backTop.classList.toggle('visible',scrollable&&window.scrollY>360)}
backTop.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});window.addEventListener('scroll',updateBackTop,{passive:true});window.addEventListener('resize',updateBackTop,{passive:true});new ResizeObserver(updateBackTop).observe(document.documentElement);document.addEventListener('toggle',()=>requestAnimationFrame(updateBackTop),true);
async function collect(n){if(n===300){try{if(typeof SUMMARIES!=='undefined'&&SUMMARIES?.[300]?.sections)return SUMMARIES[300].sections.map((x,i)=>({episode:n,order:i,time:shiftTime(x.time),end:x.end?shiftTime(x.end):null,title:String(x.title||'').replace(/^\s*\d+\)\s*/,''),points:[...(x.items||[])]}))}catch{}}
const a=document.createElement('article');a.hidden=true;a.innerHTML=`<h2>Podcast ${n}</h2>`;episodesBox.append(a);for(let wait=0;wait<120&&!a.querySelector('.summary-block');wait++)await new Promise(r=>requestAnimationFrame(r));shiftSummaryTimes(a);const out=[...a.querySelectorAll('.summary-block')].map((b,i)=>({episode:n,order:i,time:b.querySelector('.summary-time')?.textContent||'0:00',end:b.dataset.end?shiftTime(b.dataset.end):null,title:b.querySelector('.summary-title')?.textContent||`Otázka ${i+1}`,points:[...b.querySelectorAll('li')].map(x=>x.textContent.trim())}));a.remove();return out}
const terms=()=>norm(search.value.trim()).split(/\s+/).filter(Boolean),highlightTerms=()=>[...new Set([...terms(),...(topic==='Vše'?[]:(MAP[topic]||[]).map(norm))])].sort((a,b)=>b.length-a.length),titleText=x=>norm(x.title),answerText=x=>norm(x.points.join(' ')),text=x=>`${titleText(x)} ${answerText(x)}`;
function matchLevel(x){const ts=terms();if(!ts.length)return 0;const title=titleText(x),answer=answerText(x),episode=String(x.episode);if(ts.every(k=>title.includes(k)||episode.includes(k)))return 0;if(ts.some(k=>title.includes(k)||episode.includes(k)))return 1;if(ts.every(k=>answer.includes(k)))return 2;if(ts.every(k=>`${title} ${answer}`.includes(k)||episode.includes(k)))return 3;return 99}
function ok(x){const t=text(x);return(topic==='Vše'||MAP[topic].some(k=>t.includes(norm(k))))&&matchLevel(x)<99}
const isFiltered=()=>terms().length>0||topic!=='Vše';
const allLoaded=()=>loadedEpisodes.size>=FAQ.length;
const loadOrder=()=>questionSort.value==='old'?[...FAQ].reverse():FAQ;
function loadedPrefix(){const set=new Set();for(const n of loadOrder()){if(!loadedEpisodes.has(n))break;set.add(n)}return set}
function computeShown(){const mode=questionSort.value,prefix=!isFiltered()&&!allLoaded()?loadedPrefix():null;return all.filter(x=>(!prefix||prefix.has(x.episode))&&ok(x)).map(x=>({...x,match:matchLevel(x)})).sort((a,b)=>a.match-b.match||(mode==='old'?a.episode-b.episode:b.episode-a.episode)||a.order-b.order)}
function countLabel(n){return n===1?'1 nalezená otázka':n>=2&&n<=4?`${n} nalezené otázky`:`${n} nalezených otázek`}
function updateCount(){if(!active)return;count.textContent=isFiltered()?countLabel(shown.length):`${TOTAL_QUESTIONS} otázek`}
function nextEpisode(){return loadOrder().find(n=>!loadedEpisodes.has(n))}
function loadEpisode(n){if(n==null||loadedEpisodes.has(n))return Promise.resolve();if(episodeJobs.has(n))return episodeJobs.get(n);const job=loadQueue.then(async()=>{if(loadedEpisodes.has(n))return;let items=[];try{items=await collect(n)}catch(_){}loadedEpisodes.add(n);all.push(...items)});loadQueue=job.catch(()=>{});episodeJobs.set(n,job);job.finally(()=>episodeJobs.delete(n));return job}
async function loadUntilVisible(target,generation=filterGeneration){while(generation===filterGeneration&&computeShown().length<target){const n=nextEpisode();if(n==null)break;await loadEpisode(n)}shown=computeShown();updateCount()}
async function loadAll(generation=filterGeneration){while(generation===filterGeneration&&!allLoaded()){const n=nextEpisode();if(n==null)break;await loadEpisode(n)}shown=computeShown();updateCount()}
function hi(value){const raw=String(value),ts=highlightTerms();if(!ts.length)return esc(raw);const n=norm(raw),ranges=[];for(const t of ts){if(!t)continue;let at=0;while((at=n.indexOf(t,at))>=0){ranges.push([at,at+t.length]);at+=Math.max(1,t.length)}}ranges.sort((a,b)=>a[0]-b[0]||b[1]-a[1]);const merged=[];for(const r of ranges){const last=merged.at(-1);if(last&&r[0]<=last[1])last[1]=Math.max(last[1],r[1]);else merged.push([...r])}let out='',pos=0;for(const [a,b] of merged){out+=esc(raw.slice(pos,a))+`<mark>${esc(raw.slice(a,b))}</mark>`;pos=b}return out+esc(raw.slice(pos))}
function mathText(value){let out=String(value);out=out.replace(/\b([A-Za-z]|10)\s*\^\s*\{?(-?\d+)\}?/g,'\\($1^{$2}\\)').replace(/\b([A-Za-z])([²³])\b/g,(m,b,p)=>`\\(${b}^{${p==='²'?'2':'3'}}\\)`);return out}
function rich(value){return hi(mathText(value))}
function card(x,i){const cats=Object.entries(MAP).filter(([n,k])=>n!=='Vše'&&k.some(v=>text(x).includes(norm(v)))).slice(0,3).map(([n])=>`<span class="tag">${esc(n)}</span>`).join('');return`<article class="faq-question-card" data-i="${i}"><div class="date faq-meta">Díl ${x.episode} • ${esc(x.time)}</div><h2>${rich(x.title)}</h2><div class="desc faq-answer"><ul>${x.points.map(p=>`<li>${rich(p)}</li>`).join('')}</ul></div><div class="tags">${cats}</div><div class="links"><button class="faq-play" type="button">Přehrát</button><button class="faq-more" type="button">Číst více</button></div></article>`}
function typeset(root=view){if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([root]).catch(()=>{})}
function ensureMathJax(){if(window.MathJax?.typesetPromise||document.querySelector('script[data-vedator-mathjax]'))return;window.MathJax={tex:{inlineMath:[['\\(','\\)']],processEscapes:true},options:{skipHtmlTags:['script','noscript','style','textarea','pre','code']}};const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js';s.async=true;s.dataset.vedatorMathjax='1';s.onload=()=>typeset(document);document.head.append(s)}
function checkMore(){requestAnimationFrame(()=>{view.querySelectorAll('.faq-question-card').forEach(c=>{const a=c.querySelector('.faq-answer'),b=c.querySelector('.faq-more');if(!a||!b)return;b.classList.toggle('hidden',a.scrollHeight<=a.clientHeight+2)});updateBackTop();typeset(view)})}
function observeSentinel(){io?.disconnect();const s=view.querySelector('.faq-sentinel');if(!active||!s||allLoaded()&&rendered>=shown.length)return;io=new IntersectionObserver(entries=>{if(entries.some(x=>x.isIntersecting))void loadNextBatch()},{rootMargin:'500px 0px'});io.observe(s)}
function appendBatch(){view.querySelector('.faq-sentinel')?.remove();const end=Math.min(rendered+BATCH,shown.length);if(end>rendered)view.insertAdjacentHTML('beforeend',shown.slice(rendered,end).map((x,i)=>card(x,rendered+i)).join(''));rendered=end;if(rendered<shown.length||!allLoaded())view.insertAdjacentHTML('beforeend','<div class="faq-sentinel" aria-hidden="true"></div>');checkMore();if(!loading)observeSentinel()}
async function loadNextBatch(){if(loading||!active)return;const generation=filterGeneration,target=rendered+BATCH;loading=true;try{shown=computeShown();if(shown.length<target&&!allLoaded())await loadUntilVisible(target,generation);if(generation!==filterGeneration)return;shown=computeShown();if(rendered<shown.length)appendBatch()}finally{loading=false;if(active)requestAnimationFrame(observeSentinel)}}
function maybeLoadNextBatch(){if(!active||loading)return;const s=view.querySelector('.faq-sentinel');if(!s)return;const rect=s.getBoundingClientRect();if(rect.top<=window.innerHeight+500&&rect.bottom>=-500)void loadNextBatch()}
window.addEventListener('scroll',maybeLoadNextBatch,{passive:true});window.addEventListener('resize',maybeLoadNextBatch,{passive:true});
async function filter(){const generation=++filterGeneration;io?.disconnect();rendered=0;view.innerHTML='<div class="faq-loading">Načítám otázky…</div>';if(isFiltered()){if(active)count.textContent='Hledám otázky…';await loadAll(generation)}else await loadUntilVisible(BATCH,generation);if(generation!==filterGeneration)return;shown=computeShown();view.innerHTML='';updateCount();appendBatch();syncQuestionButtons();requestAnimationFrame(updateBackTop)}
function show(on){active=on;view.classList.toggle('hidden',!on);qtopics.classList.toggle('hidden',!on);questionSort.classList.toggle('hidden',!on);if(!on){questionSort.classList.add('hidden');io?.disconnect();return}window.__vedatorActiveView='questions';document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.toggle('active',x===tab));episodesBox.classList.add('hidden');seriesBox.classList.add('hidden');document.querySelector('.vedator-playlist-view')?.classList.remove('active');document.querySelector('.vedator-data-view')?.classList.remove('active');topics.classList.add('hidden');episodeSort?.classList.add('hidden');seriesSort?.classList.add('hidden');ensureMathJax();updateCount();if(!all.length)filter();else{shown=computeShown();if(!view.children.length)appendBatch();else requestAnimationFrame(observeSentinel)}requestAnimationFrame(updateBackTop)}
tab.onclick=()=>show(true);tabs.querySelectorAll('.tab').forEach(x=>{if(x!==tab)x.addEventListener('click',()=>show(false))});
window.addEventListener('vedatorlanguagechange',()=>{if(!active&&currentView()!=='questions')return;const restore=()=>{if(active||currentView()==='questions')show(true)};queueMicrotask(restore);requestAnimationFrame(()=>requestAnimationFrame(restore))});
search.addEventListener('input',event=>{if(!active)return;event.stopImmediatePropagation();filter()},true);questionSort.addEventListener('change',filter);
qtopics.onclick=e=>{const b=e.target.closest('.topic');if(!b)return;topic=b.dataset.topic;qtopics.querySelectorAll('.topic').forEach(x=>x.classList.toggle('active',x===b));filter()};
function endOfQuestion(q){if(q.end)return sec(q.end);const next=all.find(x=>x.episode===q.episode&&x.order===q.order+1);return next?sec(next.time):Infinity}
function contextItems(){return shown.map(q=>({episode:q.episode,time:sec(q.time),end:endOfQuestion(q)}))}
function bindAudio(){const audio=document.querySelector('.vedator-audio-card audio');if(!audio||audio.__vedatorQuestionAuto)return;audio.__vedatorQuestionAuto=true;audio.addEventListener('timeupdate',()=>{const ctx=window.__vedatorQuestionContext;if(!ctx||autoBusy)return;const current=ctx.items[ctx.index];if(!current||!Number.isFinite(current.end)||audio.currentTime<current.end-.15)return;autoBusy=true;audio.pause();if(ctx.index<ctx.items.length-1)go(1);else{audio.currentTime=current.end;window.__vedatorQuestionContext=null;syncQuestionButtons()}setTimeout(()=>{autoBusy=false},700)});syncQuestionButtons()}
function syncQuestionButtons(){const c=window.__vedatorQuestionContext,r=document.querySelector('.vedator-question-controls');if(c&&r){const p=r.querySelector('.previous-question'),n=r.querySelector('.next-question');if(p)p.disabled=c.index<=0;if(n)n.disabled=c.index>=c.items.length-1}bindAudio()}
function watchAudioCard(){audioObserver?.disconnect();audioObserver=new MutationObserver(syncQuestionButtons);audioObserver.observe(document.body,{childList:true,subtree:true})}watchAudioCard();document.addEventListener('play',syncQuestionButtons,true);document.addEventListener('loadedmetadata',syncQuestionButtons,true);
function play(i){const x=shown[i],e=ep(x.episode);if(!x||!e?.enclosure)return;window.__vedatorQuestionContext={items:contextItems(),index:i};window.__vedatorRequestedStart={episode:x.episode,time:sec(x.time),createdAt:Date.now()};const a=document.createElement('article');a.hidden=true;a.innerHTML='<h2></h2><div class="links"><a class="primary"></a></div>';a.querySelector('h2').textContent=e.title;const l=a.querySelector('a');l.href=e.enclosure;l.dataset.vedatorEpisodeTitle=e.title;document.body.append(a);l.click();a.remove();requestAnimationFrame(syncQuestionButtons)}
view.onclick=e=>{const c=e.target.closest('.faq-question-card');if(!c)return;if(e.target.closest('.faq-more')){c.classList.toggle('open');e.target.textContent=c.classList.contains('open')?'Číst méně':'Číst více';window.dispatchEvent(new Event('vedatorcontentchange'));requestAnimationFrame(updateBackTop)}else if(e.target.closest('.faq-play'))play(Number(c.dataset.i))};
function go(d){const c=window.__vedatorQuestionContext;if(!c)return;const ni=c.index+d;if(ni<0||ni>=c.items.length)return;const t=c.items[ni];c.index=ni;const card=document.querySelector('.vedator-audio-card'),audio=card?.querySelector('audio'),n=Number(String(card?.querySelector('.vedator-audio-card__title')?.textContent||'').match(/\b(\d+)\b/)?.[1]);if(n===t.episode&&audio){audio.currentTime=t.time;audio.play().catch(()=>{});syncQuestionButtons();return}const i=shown.findIndex(x=>x.episode===t.episode&&sec(x.time)===t.time);if(i>=0)play(i);syncQuestionButtons()}
document.addEventListener('click',e=>{const b=e.target.closest('.vedator-question-btn');if(!b||!window.__vedatorQuestionContext)return;e.preventDefault();e.stopImmediatePropagation();go(b.classList.contains('previous-question')?-1:1)},true);
requestAnimationFrame(updateBackTop);
})();
