const CACHE='vedator-temata-v125-sk';
const VERSION='v125-sk';
const ASSETS=['./','index.html','manifest.webmanifest','icon.svg','fast-touch.css','audio-player.css','audio-player.js','catalog-patch.js','custom-player.js','theme-toggle.js','ui-cleanup.js','highlight-patch.js','playlist-patch.js','slovak-topics-patch.js','topic-filter-fix.js','data-backup.js','view-layout-fix.js','title-truncate.js','scientist-title-fix.js','media-session-skip.js','lazy-render.js','episode-300-chapters.js','question-controls-stability.js','episode-17-summary.js','episode-26-summary.js','episode-35-summary.js','episode-51-summary.js','episode-60-summary.js','episode-69-summary.js','episode-138-summary.js','episode-75-summary.js','episode-82-summary.js','episode-89-summary.js','episode-100-summary.js','episode-112-summary.js','episode-119-chapters.js','episode-119-summary.js','episode-128-chapters.js','episode-128-summary.js','episode-133-chapters.js','episode-133-summary.js','episode-143-chapters.js','episode-143-summary.js','episode-158-chapters.js','episode-158-summary.js','episode-179-chapters.js','episode-179-summary.js','episode-190-218-226-chapters.js','episode-190-summary.js','episode-203-chapters.js','episode-203-summary.js','episode-211-chapters.js','episode-211-summary.js','episode-218-summary.js','episode-226-summary.js','episode-244-chapters.js','episode-244-summary.js','episode-248-chapters.js','episode-248-summary.js','episode-257-chapters.js','episode-257-summary.js','episode-263-summary.js','episode-270-summary.js','episode-272-summary.js','episode-278-summary.js','episode-284-summary.js','episode-289-summary.js','episode-295-summary.js','episode-313-summary.js','episode-319-summary.js','episode-326-summary.js','episode-332-summary.js','episode-337-summary.js','episode-340-summary.js','questions-view.js','language-switch.css','language-switch.js'];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener('activate',e=>e.waitUntil((async()=>{await Promise.all((await caches.keys()).filter(k=>k!==CACHE&&(!/-(?:sk|cs)$/.test(k)||k.endsWith('-sk')))/*VEDATOR_LOCALE_CACHE_GUARD*/.map(k=>caches.delete(k)));await self.clients.claim();for(const c of await self.clients.matchAll({type:'window',includeUncontrolled:true}))c.postMessage({type:'VEDATOR_SW_UPDATED',version:VERSION})})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
function updaterScript(){return `<script>(()=>{if(!('serviceWorker'in navigator)||window.__vedatorSwUpdater)return;window.__vedatorSwUpdater=true;let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()});navigator.serviceWorker.addEventListener('message',event=>{if(event.data&&event.data.type==='VEDATOR_SW_UPDATED'&&!sessionStorage.getItem('vedator-sw-'+event.data.version)){sessionStorage.setItem('vedator-sw-'+event.data.version,'1');location.reload()}});navigator.serviceWorker.ready.then(reg=>{reg.update().catch(()=>{});if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)worker.postMessage({type:'SKIP_WAITING'})})})}).catch(()=>{});document.addEventListener('visibilitychange',()=>{if(!document.hidden)navigator.serviceWorker.ready.then(reg=>reg.update()).catch(()=>{})});})();</script>`}
function addNumbers(source,numbers,prepend=false){const values=source.split(',').map(v=>v.trim()).filter(Boolean);for(const n of numbers)if(!values.includes(String(n)))prepend?values.unshift(String(n)):values.push(String(n));return values.join(',')}
async function patchFaqCode(response,url){
 if(!response||!['questions-view.js','playlist-patch.js','question-controls-stability.js'].includes(url.pathname.split('/').pop()))return response;
 let code=await response.text();
 if(url.pathname.endsWith('questions-view.js')||url.pathname.endsWith('playlist-patch.js'))code=code.replace(/const FAQ=\[([^\]]*)\]/,(_,x)=>`const FAQ=[${addNumbers(x,[17,26,35,51,60,69,75,138])}]`);
 if(url.pathname.endsWith('question-controls-stability.js')){
  code=code.replace(/for\(const src of \[([^\]]*)\]\)/,(_,x)=>{let y=x;for(const n of [17,26,35,51,60,69,75,138])if(!y.includes(`episode-${n}-summary.js`))y+=`, './episode-${n}-summary.js'`;return `for(const src of [${y}])`});
  code=code.replace(/const FAQ_EPISODES=new Set\(\[([^\]]*)\]\)/,(_,x)=>`const FAQ_EPISODES=new Set([${addNumbers(x,[17,26,35,51,60,69,75,138],true)}])`);
 }
 const h=new Headers(response.headers);h.delete('content-length');h.delete('content-encoding');h.set('content-type','application/javascript; charset=utf-8');return new Response(code,{status:response.status,statusText:response.statusText,headers:h});
}
async function injectEnhancements(response){
 if(!response)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();
 const css=['fast-touch.css','audio-player.css'];for(const f of css)if(!html.includes(f))html=html.replace('</head>',`<link rel="stylesheet" href="./${f}"></head>`);
 const js=['audio-player.js','catalog-patch.js','custom-player.js','theme-toggle.js','ui-cleanup.js','slovak-topics-patch.js','topic-filter-fix.js','highlight-patch.js','playlist-patch.js','data-backup.js','view-layout-fix.js','title-truncate.js','scientist-title-fix.js','media-session-skip.js','lazy-render.js','episode-300-chapters.js','question-controls-stability.js','episode-17-summary.js','episode-26-summary.js','episode-35-summary.js','episode-51-summary.js','episode-60-summary.js','episode-69-summary.js','episode-138-summary.js','episode-75-summary.js','episode-82-summary.js','episode-89-summary.js','episode-100-summary.js','episode-112-summary.js','episode-119-chapters.js','episode-119-summary.js','episode-128-chapters.js','episode-128-summary.js','episode-133-chapters.js','episode-133-summary.js','episode-143-chapters.js','episode-143-summary.js','episode-158-chapters.js','episode-158-summary.js','episode-179-chapters.js','episode-179-summary.js','episode-190-218-226-chapters.js','episode-190-summary.js','episode-203-chapters.js','episode-203-summary.js','episode-211-chapters.js','episode-211-summary.js','episode-218-summary.js','episode-226-summary.js','episode-244-chapters.js','episode-244-summary.js','episode-248-chapters.js','episode-248-summary.js','episode-257-chapters.js','episode-257-summary.js','episode-263-summary.js','episode-270-summary.js','episode-272-summary.js','episode-278-summary.js','episode-284-summary.js','episode-289-summary.js','episode-295-summary.js','episode-313-summary.js','episode-319-summary.js','episode-326-summary.js','episode-332-summary.js','episode-337-summary.js','episode-340-summary.js','questions-view.js','language-switch.js'];
 for(const f of js)if(!html.includes(f))html=html.replace('</body>',`<script src="./${f}" defer></script></body>`);
 if(!html.includes('__vedatorSwUpdater'))html=html.replace('</body>',updaterScript()+'</body>');const headers=new Headers(response.headers);headers.delete('content-length');headers.delete('content-encoding');headers.set('content-type','text/html; charset=utf-8');headers.set('cache-control','no-store');return new Response(html,{status:response.status,statusText:response.statusText,headers});
}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url),isMedia=event.request.destination==='audio'||event.request.headers.has('range')||/\.(?:mp3|m4a|aac|ogg|wav|webm)(?:$|\?)/i.test(url.pathname);if(isMedia||url.origin!==self.location.origin)return;const isPage=event.request.mode==='navigate'||url.pathname.endsWith('/index.html')||url.pathname.endsWith('/vedator/'),isAppCode=isPage||/\.(?:js|css|json|webmanifest)$/i.test(url.pathname);if(isAppCode){event.respondWith((async()=>{try{let r=await fetch(event.request,{cache:'no-store'});if(isPage)r=await injectEnhancements(r);else r=await patchFaqCode(r,url);const copy=r.clone();caches.open(CACHE).then(c=>c.put(event.request,copy)).catch(()=>{});return r}catch(error){let cached=await caches.match(event.request)||await caches.match('./');if(!cached)throw error;return isPage?injectEnhancements(cached):patchFaqCode(cached,url)}})());return}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(event.request,copy)).catch(()=>{});return r}))) });